/**
 * Generated project configuration files.
 */

import type { VirtualFile } from '../types';

/** Generate the tsconfig.json file for the generated project. */
export function generateTsConfig(): VirtualFile {
    const content = JSON.stringify(
        {
            compilerOptions: {
                target: 'ES2022',
                useDefineForClassFields: true,
                lib: ['ES2022', 'DOM', 'DOM.Iterable'],
                module: 'ESNext',
                skipLibCheck: true,
                moduleResolution: 'bundler',
                allowImportingTsExtensions: true,
                verbatimModuleSyntax: true,
                moduleDetection: 'force',
                noEmit: true,
                jsx: 'react-jsx',
                strict: true,
                noUnusedLocals: true,
                noUnusedParameters: true,
                noFallthroughCasesInSwitch: true,
                noUncheckedSideEffectImports: true,
                baseUrl: '.',
                paths: {
                    '@/*': ['./src/*'],
                },
            },
            include: ['src'],
        },
        null,
        4,
    );

    return {
        path: 'tsconfig.json',
        content: `${content}\n`,
    };
}

/** Generate the vite.config.ts file for the generated project. */
export function generateViteConfig(): VirtualFile {
    const content = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
    plugins: [react()],
    resolve: {
        alias: {
            '@': '/src',
        },
    },
});
`;

    return {
        path: 'vite.config.ts',
        content,
    };
}

/** Generate the postcss.config.js file for the generated project. */
export function generatePostcssConfig(): VirtualFile {
    const content = `export default {
    plugins: {
        tailwindcss: {},
        autoprefixer: {},
    },
};
`;

    return {
        path: 'postcss.config.js',
        content,
    };
}

/** Generate the README.md file for the generated project. */
export function generateReadme(projectName: string): VirtualFile {
    const content = `# ${projectName}

Generated by **FramerX** — the Framer-to-Code compiler.

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Project Structure

\`\`\`
src/
    components/   Reusable React components
    sections/     Page sections
    styles/       Global styles (Tailwind)
    App.tsx       Main application
    main.tsx      Entry point
\`\`\`

## Scripts

| Script | Description |
| --- | --- |
| \`npm run dev\` | Start the dev server |
| \`npm run build\` | Build for production |
| \`npm run preview\` | Preview the production build |
| \`npm run lint\` | Lint the codebase |
| \`npm run format\` | Format with Prettier |

## Tech Stack

- **React 19** — UI framework
- **TypeScript** — Strict type checking
- **Tailwind CSS** — Utility-first styling
- **Motion** — Animations
- **Vite** — Build tooling
`;

    return {
        path: 'README.md',
        content,
    };
}

/** Generate the .gitignore file for the generated project. */
export function generateGitignore(): VirtualFile {
    const content = `# Dependencies
node_modules/

# Build outputs
dist/
dist-ssr/
*.local

# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

# Editor
.vscode/*
!.vscode/extensions.json
.idea/
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# TypeScript
*.tsbuildinfo
`;

    return {
        path: '.gitignore',
        content,
    };
}

/** Generate the .prettierrc file matching the compiler's formatter options. */
export function generatePrettierConfig(): VirtualFile {
    const content = JSON.stringify(
        {
            printWidth: 120,
            tabWidth: 4,
            semi: true,
            singleQuote: true,
            trailingComma: 'all',
        },
        null,
        4,
    );

    return {
        path: '.prettierrc',
        content: `${content}\n`,
    };
}

/** Generate the eslint.config.js file for the generated project. */
export function generateEslintConfig(): VirtualFile {
    const content = `import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';

export default tseslint.config(
    { ignores: ['dist'] },
    {
        extends: [js.configs.recommended, ...tseslint.configs.recommended],
        files: ['**/*.{ts,tsx}'],
        languageOptions: {
            ecmaVersion: 2022,
            globals: globals.browser,
        },
        plugins: {
            'react-hooks': reactHooks,
            'react-refresh': reactRefresh,
        },
        rules: {
            ...reactHooks.configs.recommended.rules,
            'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
        },
    },
);
`;

    return {
        path: 'eslint.config.js',
        content,
    };
}